import { useNavigate } from "react-router"
import { useState, useEffect } from "react"
import { UpdateUser } from "../services/Authorize"
import axios from "axios"
import { BASE_URL } from "../globals"